### ISSUE TITLE
Remove Gem dependency on compass-html5

### ISSUE THREAD

**Issue by dim** [sporkd/html5-rails#1]
Please remove the `s.add_dependency "compass-html5", "~> 0.0.1"` line for your gemspec. People may want to include it separately within the `:assets` group.

Thanks, D

**Comment by sporkd** [comment]
This is interesting.  It is in fact a hard dependency for any compilation to work at all.  But I see your point. This will just makes it a little harder to explain that both gems are required in your gemfile.  Guess it's about time for a readme.

**Comment by sporkd** [comment]
This was a good idea.  Fixed a while back:

https://github.com/sporkd/html5-rails/commit/e5e560021f45a646aba000663641890a07cac7d9
