### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by remon** [sporkd/html5-rails#24]
used these gem on my application and It was working on IE like on chrome and firefox and opera too ,,,it was great ,,till I updated my ruby version to  1.9.3 and I found always encoding error ,,,and the gem not working ,,,I returned back to ruby 1.8.7 and i followed all steps for these gem but still not working on ...do you know what is the problem

**Comment by sporkd** [comment]
I'd need more information on what kind of error you were seeing.

**Comment by remon** [comment]
actually in internet explorer its not working I am newbie to html5 but I have audio tags and i am using pjax on my app  and here is my _head.html.erb

```
   <head>
  <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

  <title><%=@title%></title>

   <meta name="description" content="">
 <meta name="viewport" content="width=device-width">

   <%= render "stylesheets" %>
   <%= javascript_include_tag "polyfills" %>
<%= javascript_include_tag "application"%>

   <!--[if lt IE 9]>
  <script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
  <![endif]-->

   <%= csrf_meta_tag %>
      </head>
```

and I am replacing twitter bottstrap with normalize css and putting it on the top of my stylesheets .
and its not working on internet explorer

**Comment by sporkd** [comment]
You still have not provided me with any details on what is not working, or what version (or versions) of IE. I would take a look at your javascript console and see if it's causing any errors. But other than that I have no idea how to help you.
