### ISSUE TITLE
Do I have to run `compass init --using blueprint`?

### ISSUE THREAD

**Issue by jmuheim** [sporkd/html5-rails#27]
Hey there

Thanks a lot for this very useful gem. For our project, we want to use HTML5-Rails in combination with SASS/Compass and Blueprint. I'm a bit unsure what to do now.

On the SASS/Compass page is mentioned that I should simply run `compass init --using blueprint`, but I don't know whether this generator is also intended to run on a HTML5-Rails "gemmed" copy of Rails?

Thanks a lot for help,
Josh

**Comment by sporkd** [comment]
The rails generators will be much more helpful if you're wanting H5bp, and it does not include blueprint.  Running `compass init` will probably _NOT_ generate files in the right place for you. So if you want blueprint I would suggest running `compass init --using blueprint` in a separate stand-alone compass project and copying over the parts and files you want into your rails app.

**Comment by jmuheim** [comment]
That's exactly how I've done it. Thanks for making this clear.

**Comment by jmuheim** [comment]
I think I'll stop spamming your issues tracker now. :wink:
