### ISSUE TITLE
`rails generate html5:install` with Sass instead of SCSS?

### ISSUE THREAD

**Issue by jmuheim** [sporkd/html5-rails#28]
Is there a way to tell the installer to generate Sass files instead of SCSS?

Thank you.

**Comment by sporkd** [comment]
The scss actually comes from the project https://github.com/sporkd/compass-h5bp, and this is not an option in html5-rails.  But have a look at the sass-convert command line utility that comes with sass.

**Comment by jmuheim** [comment]
Thank you for the information. :smiley:
