### ISSUE TITLE
cant generate html5:install

### ISSUE THREAD

**Issue by hasft** [sporkd/html5-rails#32]
hi.. im new with rails
and when i generate html5:install i got this 

Users/ME/.rvm/gems/ruby-1.9.2-p320/gems/compass-h5bp-0.1.1/lib/compass/h5bp.rb:5:in `module:H5bp': uninitialized constant Compass::Frameworks (NameError)

i dont have any experience with rails but i just want to write with haml compass and sass

how to fix this?

**Comment by sporkd** [comment]
Hi hasft. This is probably and issue with your Gemfile not having the required gems in the assets section. Make sure your Gemfile looks something like this section in the readme:
- https://github.com/sporkd/html5-rails#1-in-your-gemfile
- https://github.com/sporkd/html5-rails#notes

**Comment by hasft** [comment]
hi sporkd.. i use ruby 1.9.3.. i have to reinstall rake and sqlite3.. but its work now.. thanks anyway
