### ISSUE TITLE
h5bp templates missing in rails 4.0

### ISSUE THREAD

**Issue by twreid** [sporkd/html5-rails#33]
I just installed on a Rails 4.0 application and I had to comment everything out that dealt with h5bp as that all gave me a file unreadable error and I have no partials with those names at all.

**Comment by bglassmaker** [comment]
I think this is actually a problem with Compass not being ready for Rails 4 yet, when you run the generator you get this.

"Unsupported rails environment for compass"

I updated Compass to the alpha that is rails 4 compatible and it's all good now after running the generator again

gem "compass-rails", "~> 2.0.alpha.0"

Hope that helps.

**Comment by Showtimes** [comment]
@bglassmaker this works. Thanks

**Comment by twreid** [comment]
@bglassmaker Thanks that worked for me too.
