### ISSUE TITLE
Compatibility with ruby 1.8*

### ISSUE THREAD

**Issue by moktin** [sporkd/html5-rails#5]
Hi
Would it be possible to make that gem ruby 1.8 compatible by changing the new hash syntax in generators and views by the classical syntax ?

For example replacing : 
{class: "no-js", lang: "en"} by {:class => "no-js",  :lang => "en"}

I can pull a request if needed.

**Comment by sporkd** [comment]
Yea, that would be great.  I've just gotten in the habit of the new syntax, but since this is a library it's a good point.

peter
