### ISSUE TITLE
Generator fails to run 

### ISSUE THREAD

**Issue by Maher4Ever** [sporkd/html5-rails#7]
Hello,

Today I wanted to update a rails app to 3.1. 3.
I have already been using your other gem called `compass-html5-boilerplate` with my old 3.0 app and it worked great.

SO after reading a bit I found this repo and tried to follow the readme instructions to generate the new files, but it fails every time with the following error:
`PATH_TO_GEMS/activesupport-3.1.3/lib/active_support/dependencies.rb:240:in 'require': cannot load such file -- html5-boilerplate (LoadError)`

I cloned this gem's source, ran the tests and they pass.

Do you have any idea what might be causing this problem?

**Comment by JDutil** [comment]
I was just able to setup a new app with rails 3.1.3 and ruby 1.9.3 fine.  I would double check that you added all gems to your Gemfile and ran bundle to install them.  If you still receive an error the issue could wind up being that you need to run installer with bundle exec:

```
$ bundle exec rails generate html5:install
```

**Comment by Maher4Ever** [comment]
Ok, so the problem was that I had a configuration file called `compass.rb` which required the old `html5-boilerplate` gem.
After commenting the whole file and running the generator, it was overwritten with the new one and now everything works.
Maybe this could be added to the readme file as an upgrade tip :).
